# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-29 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_001_PAGEPUBLIC', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='praticien',
            old_name='praticien_slug',
            new_name='slug',
        ),
    ]
