# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-29 14:59
from __future__ import unicode_literals

import APP_001_PAGEPUBLIC.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_001_PAGEPUBLIC', '0002_auto_20180829_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='praticien',
            name='praticien_image',
            field=models.ImageField(blank=True, null=True, upload_to=APP_001_PAGEPUBLIC.utils.upload_location),
        ),
        migrations.AlterField(
            model_name='praticien',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
