# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-29 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_001_PAGEPUBLIC', '0004_praticien_praticien_introduction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='praticien',
            old_name='praticien_introduction',
            new_name='praticien_presentation_texte',
        ),
    ]
