# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-29 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_001_PAGEPUBLIC', '0005_auto_20180829_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='praticien',
            name='praticien_presentation_titre',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
