# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-29 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP_001_PAGEPUBLIC', '0006_praticien_praticien_presentation_titre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation_date', models.DateField(verbose_name='Date de la formation')),
                ('formation_titre', models.CharField(max_length=300, verbose_name='Titre de la formation et organisme')),
                ('formation_commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire(s)')),
            ],
        ),
        migrations.AlterModelOptions(
            name='praticien',
            options={'verbose_name_plural': 'Praticien'},
        ),
        migrations.AlterField(
            model_name='praticien',
            name='praticien_nom',
            field=models.CharField(max_length=120, verbose_name='Nom du praticien'),
        ),
        migrations.AlterField(
            model_name='praticien',
            name='praticien_prenom',
            field=models.CharField(max_length=120, verbose_name='Prénom du praticien'),
        ),
        migrations.AlterField(
            model_name='praticien',
            name='praticien_presentation_texte',
            field=models.TextField(blank=True, null=True, verbose_name="Texte de la section 'Mon Parcours'"),
        ),
        migrations.AlterField(
            model_name='praticien',
            name='praticien_presentation_titre',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name="Titre de la section 'Mon Parcours'"),
        ),
        migrations.AlterField(
            model_name='praticien',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='formation',
            name='formation_praticien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formation', to='APP_001_PAGEPUBLIC.Praticien', verbose_name='Praticien'),
        ),
    ]
