# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-29 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_001_PAGEPUBLIC', '0007_auto_20180829_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formation',
            options={'verbose_name_plural': 'Diplôme(s) et formation(s)'},
        ),
    ]
