# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-29 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP_001_PAGEPUBLIC', '0008_auto_20180829_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_date_debut', models.DateField(verbose_name="Début de l'experience")),
                ('experience_date_fin', models.DateField(verbose_name="Fin de l'experience")),
                ('experience_titre', models.CharField(max_length=300, verbose_name="Titre de l'experience et entreprise")),
                ('experience_commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire(s)')),
                ('experience_praticien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='APP_001_PAGEPUBLIC.Praticien', verbose_name='Praticien')),
            ],
            options={
                'verbose_name_plural': 'Expérience professionnelle(s)',
            },
        ),
    ]
