# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-29 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_001_PAGEPUBLIC', '0009_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='experience_date_fin',
            field=models.DateField(auto_now_add=True, verbose_name="Fin de l'experience"),
        ),
    ]
