# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-29 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_001_PAGEPUBLIC', '0010_auto_20180829_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='experience_date_debut',
            field=models.CharField(max_length=300, verbose_name="Début de l'experience"),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_date_fin',
            field=models.CharField(max_length=300, verbose_name="Fin de l'experience"),
        ),
    ]
