# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-30 14:50
from __future__ import unicode_literals

import APP_001_PAGEPUBLIC.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_001_PAGEPUBLIC', '0012_auto_20180829_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet_titre', models.CharField(max_length=120, verbose_name='Cabinet titre')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, verbose_name='slug')),
                ('cabinet_adresse', models.CharField(max_length=200, verbose_name='Adresse postale')),
                ('cabinet_telephone', models.CharField(max_length=10, verbose_name='Téléphone')),
                ('cabinet_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('cabinet_rdvenligne', models.URLField(blank=True, max_length=300, null=True, verbose_name='Url rdv en ligne')),
                ('cabinet_description', models.TextField(blank=True, null=True, verbose_name='Texte accueil cabinet')),
                ('cabinet_acces', models.TextField(blank=True, null=True, verbose_name='Cabinet accès')),
            ],
            options={
                'verbose_name_plural': 'Cabinet',
            },
        ),
        migrations.AlterField(
            model_name='praticien',
            name='praticien_image',
            field=models.ImageField(blank=True, null=True, upload_to=APP_001_PAGEPUBLIC.utils.upload_location, verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='praticien',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, verbose_name='slug'),
        ),
    ]
