# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-30 15:11
from __future__ import unicode_literals

import APP_001_PAGEPUBLIC.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP_001_PAGEPUBLIC', '0014_auto_20180830_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinetphoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinetphoto_titre', models.CharField(max_length=120, verbose_name='Titre de la photo')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, verbose_name='slug')),
                ('cabinetphoto_photo', models.ImageField(blank=True, null=True, upload_to=APP_001_PAGEPUBLIC.utils.upload_location, verbose_name='photo du cabinet')),
                ('cabinetphoto_cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinetphoto', to='APP_001_PAGEPUBLIC.Cabinet', verbose_name='Cabinet')),
            ],
            options={
                'verbose_name_plural': 'Photos du cabinet',
            },
        ),
    ]
