# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-30 15:24
from __future__ import unicode_literals

import APP_001_PAGEPUBLIC.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_001_PAGEPUBLIC', '0015_cabinetphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession_titre', models.CharField(max_length=120, verbose_name='Profession titre')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, verbose_name='Slug')),
                ('profession_description_titre', models.CharField(max_length=120, verbose_name='Titre description profession')),
                ('profession_description_texte', models.TextField(blank=True, null=True, verbose_name='Texte description profession')),
                ('profession_img', models.ImageField(blank=True, null=True, upload_to=APP_001_PAGEPUBLIC.utils.upload_location, verbose_name='Image description profession')),
            ],
            options={
                'verbose_name_plural': 'Profession',
            },
        ),
    ]
