# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-03 15:30
from __future__ import unicode_literals

import APP_001_PAGEPUBLIC.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_001_PAGEPUBLIC', '0016_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieActe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorieacte_titre', models.CharField(max_length=120, verbose_name="Categorie d'acte")),
                ('slug', models.SlugField(blank=True, editable=False, null=True, verbose_name='Slug')),
                ('categorieacte_description', models.TextField(blank=True, null=True, verbose_name='Texte description catégorie acte')),
                ('categorieacte_cardimage', models.ImageField(blank=True, null=True, upload_to=APP_001_PAGEPUBLIC.utils.upload_location, verbose_name='Image card deck')),
                ('categorieacte_mainimage', models.ImageField(blank=True, null=True, upload_to=APP_001_PAGEPUBLIC.utils.upload_location, verbose_name='Image principale')),
            ],
            options={
                'verbose_name_plural': "Catégorie d'acte",
            },
        ),
    ]
