# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-03 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_001_PAGEPUBLIC', '0017_categorieacte'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorieacte',
            name='categorieacte_description_card',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Description card deck'),
        ),
    ]
