# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-12 15:04
from __future__ import unicode_literals

import APP_001_PAGEPUBLIC.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP_001_PAGEPUBLIC', '0018_categorieacte_categorieacte_description_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acte_titre', models.CharField(max_length=120, verbose_name='Acte')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, verbose_name='Slug')),
                ('acte_description', models.TextField(blank=True, null=True, verbose_name='Texte description acte')),
                ('acte_image', models.ImageField(blank=True, null=True, upload_to=APP_001_PAGEPUBLIC.utils.upload_location, verbose_name='Image principale')),
                ('acte_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorieacte', to='APP_001_PAGEPUBLIC.CategorieActe', verbose_name="Catégorie de l'acte")),
            ],
            options={
                'verbose_name_plural': 'Acte',
            },
        ),
    ]
